=== lainigian/2018_2019-XMLViaggi/viaggi.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="tipoViaggio">
		<xs:sequence>
			<xs:element name="id_viaggio" type="xs:integer"/>
			<xs:element name="mezzo">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="auto"/>
						<xs:enumeration value="aereo"/>
						<xs:enumeration value="treno"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="luogo_partenza" type="xs:string"/>
			<xs:element name="data_ora_partenza" type="xs:dateTime"/>
			<xs:element name="luogo_arrivo" type="xs:string"/>
			<xs:element name="data_ora_arrivo" type="xs:dateTime"/>
			<xs:element name="durata" type="xs:duration"/>
			<xs:element name="costo" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="viaggi">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="viaggio" type="tipoViaggio" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lainigian/2018_2019-XMLViaggi/viaggi.xml
<?xml version="1.0" ?>
<viaggi
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="viaggi.xsd">
	<viaggio>
		<id_viaggio>1</id_viaggio>
		<mezzo>auto</mezzo>
		<luogo_partenza>Brescia</luogo_partenza>
		<data_ora_partenza>2019-02-05T12:00:00</data_ora_partenza>
		<luogo_arrivo>Viareggio</luogo_arrivo>
		<data_ora_arrivo>2019-02-05T16:30:00</data_ora_arrivo>
		<durata>PT4H30M</durata>
		<costo>38</costo>
	</viaggio>
	<viaggio>
		<id_viaggio>2</id_viaggio>
		<mezzo>treno</mezzo>
		<luogo_partenza>Napoli</luogo_partenza>
		<data_ora_partenza>2019-02-05T08:00:00</data_ora_partenza>
		<luogo_arrivo>Roma</luogo_arrivo>
		<data_ora_arrivo>2019-02-05T10:30:00</data_ora_arrivo>
		<durata>PT2H30M</durata>
		<costo>12</costo>
	</viaggio>
</viaggi>
